#Minecraft server properties
#Tue Feb 17 07:37:38 UTC 2026
accepts-transfers=false
admin-slot=false
allow-flight=false
allow-nether=true
broadcast-console-to-ops=true
broadcast-rcon-to-ops=true
bug-report-link=
difficulty=easy
enable-command-block=false
enable-jmx-monitoring=false
enable-query=true
enable-rcon=false
enable-status=true
enforce-secure-profile=true
enforce-whitelist=true
entity-broadcast-range-percentage=100
force-gamemode=false
function-permission-level=2
gamemode=survival
generate-structures=true
generator-settings={}
grow-trees=true
hardcore=false
hellworld=false
hide-online-players=false
initial-disabled-packs=
initial-enabled-packs=vanilla
level-name=world
level-seed=86249712351165
level-type=minecraft\:normal
log-ips=true
max-chained-neighbor-updates=1000000
max-connections=3
max-players=4
max-tick-time=600000
max-world-size=29999984
monsters=false
motd=nitrado.net gameserver
network-compression-threshold=256
no-animals=false
online-mode=true
op-permission-level=4
player-idle-timeout=0
port=10170
prevent-proxy-connections=false
public=true
pvp=true
query.port=10171
rate-limit=0
rcon.password=
rcon.port=10175
region-file-compression=deflate
require-resource-pack=false
resource-pack=
resource-pack-id=
resource-pack-prompt=
resource-pack-sha1=
server-ip=5.83.169.7
server-name=nitrado.net gameserver
server-port=10170
simulation-distance=10
spawn-animals=true
spawn-monsters=true
spawn-npcs=true
spawn-protection=16
sync-chunk-writes=true
text-filtering-config=
use-native-transport=true
verify-names=true
view-distance=8
white-list=true
